application: di-game-server
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /api.*
  script: main.app

- url: /
  static_files: static/index.html
  upload: static/index.html
  login: required
  secure: always

- url: /(.+)
  static_files: static/\1
  upload: static/(.+)

libraries:
- name: webapp2
  version: "latest"
